/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Medida;
import Negocio.Obra;
import Modelo.Puesto;
import Modelo.Riesgo;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Ventana para modificar Puestos
 */

public class ADMINModificarElPuesto extends javax.swing.JFrame {

    /**
     * Creates new form ADMINModificarElPuesto
     */
    private Obra obra;
    private String identificacion;
    private Puesto puestoModificando;
    
    public ADMINModificarElPuesto(Obra obra, String identificacion) {
        this.obra = obra;       
        this.identificacion = identificacion;
        puestoModificando = obra.buscarPuesto(identificacion);
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        LabelPuesto.setText(puestoModificando.getNombre());
        
        String rutaImagen = puestoModificando.getRutaImagen();
        URL recurso = getClass().getResource(rutaImagen);
        
      if (recurso != null) {
            ImageIcon iconoImagen = new ImageIcon(recurso);
            Icon mIcono = new ImageIcon(iconoImagen.getImage()
                    .getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH));
            LabelFoto.setIcon(mIcono);
        } else {
            LabelFoto.setText("Sin imagen");
            LabelFoto.setHorizontalAlignment(SwingConstants.CENTER);
        }
        
       
        cargarRiesgosEnTabla();
        cargarMedidasEnTabla();
        
    }
    
    // Método para cargar la imagen desde una ruta
    private ImageIcon cargarImagen(String ruta) {
        try {
            return new ImageIcon(ruta); // Intentar cargar la imagen
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
            return null;
        }
    }
    
    // Método para cargar los riesgos en la tabla
    private void cargarRiesgosEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaRiesgos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Riesgo riesgo : puestoModificando.getRiesgos()) {
            modelo.addRow(new Object[]{riesgo.getNombre()});
        }
    }

    // Método para cargar las medidas en la tabla
    private void cargarMedidasEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMedidas.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Medida medida : puestoModificando.getMedidas()) {
            modelo.addRow(new Object[]{medida.getNombre()});
        }
    }

    // Método para agregar una fila a una tabla
    private void agregarFila(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.addRow(new Object[]{""}); // Agregar fila vacía para que el usuario ingrese un valor
    }

    // Método para guardar los cambios
    private void guardarCambios() {
        // Actualizar los riesgos
        ArrayList<Riesgo> nuevosRiesgos = new ArrayList<>();
        DefaultTableModel modeloRiesgos = (DefaultTableModel) tablaRiesgos.getModel();
        for (int i = 0; i < modeloRiesgos.getRowCount(); i++) {
            String nombre = modeloRiesgos.getValueAt(i, 0).toString().trim();
            if (!nombre.isEmpty()) {
                nuevosRiesgos.add(new Riesgo(nombre));
            }
        }
        puestoModificando.setRiesgos(nuevosRiesgos);

        // Actualizar las medidas
        ArrayList<Medida> nuevasMedidas = new ArrayList<>();
        DefaultTableModel modeloMedidas = (DefaultTableModel) tablaMedidas.getModel();
        for (int i = 0; i < modeloMedidas.getRowCount(); i++) {
            String nombre = modeloMedidas.getValueAt(i, 0).toString().trim();
            if (!nombre.isEmpty()) {
                nuevasMedidas.add(new Medida(nombre));
            }
        }
        puestoModificando.setMedidas(nuevasMedidas);

        JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelPuesto = new javax.swing.JLabel();
        LabelFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRiesgos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMedidas = new javax.swing.JTable();
        ButtonGuardar = new javax.swing.JButton();
        ButtonAgregarRiesgo = new javax.swing.JButton();
        ButtonAgregarMedida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Puesto:");

        LabelPuesto.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        LabelPuesto.setText("_");

        tablaRiesgos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Riesgos"
            }
        ));
        jScrollPane1.setViewportView(tablaRiesgos);

        tablaMedidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Medidas"
            }
        ));
        jScrollPane2.setViewportView(tablaMedidas);

        ButtonGuardar.setText("Guardar Cambios");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });

        ButtonAgregarRiesgo.setText("Agregar Riesgo");
        ButtonAgregarRiesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarRiesgoActionPerformed(evt);
            }
        });

        ButtonAgregarMedida.setText("Agregar Medida");
        ButtonAgregarMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarMedidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(LabelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAgregarRiesgo)
                        .addGap(160, 160, 160)
                        .addComponent(ButtonAgregarMedida)
                        .addGap(56, 56, 56)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonGuardar)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPuesto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAgregarRiesgo)
                    .addComponent(ButtonAgregarMedida))
                .addGap(12, 12, 12)
                .addComponent(ButtonGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        // TODO add your handling code here:
        guardarCambios();
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonAgregarRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarRiesgoActionPerformed
        // TODO add your handling code here:
        agregarFila(tablaRiesgos);
    }//GEN-LAST:event_ButtonAgregarRiesgoActionPerformed

    private void ButtonAgregarMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarMedidaActionPerformed
        // TODO add your handling code here:
        agregarFila(tablaMedidas);
    }//GEN-LAST:event_ButtonAgregarMedidaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarMedida;
    private javax.swing.JButton ButtonAgregarRiesgo;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel LabelPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaMedidas;
    private javax.swing.JTable tablaRiesgos;
    // End of variables declaration//GEN-END:variables
}
