/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;

import Modelo.Empleado;
import Negocio.Obra;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Clase para la ventana para la gestión de empleados
 */
public class ADMINEditorEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form PlanillaEmpleados
     */
    private Obra obra;
    
    public ADMINEditorEmpleados(Obra obra) {
        this.obra = obra;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Identificación");
        model.addColumn("Nombre");
        model.addColumn("Correo");
        model.addColumn("Teléfono");
        model.addColumn("Dirección");
        model.addColumn("Fecha Ingreso");
        model.addColumn("Salario Hora");
        model.addColumn("Puesto");

        TablaEmpleados.setModel(model);
        TablaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cargarEmpleadosEnTabla();
   
    
    
        
    }
    
    // Método para rellenar la tabla con los datos del ArrayList<Empleado>
private void cargarEmpleadosEnTabla() {
    // Obtener el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) TablaEmpleados.getModel();

    // Limpiar cualquier dato previo en la tabla
    modelo.setRowCount(0);

    // Obtener la lista de empleados
    ArrayList<Empleado> empleados = obra.getPlanillaEmpleados();

    // Recorrer el ArrayList y agregar los datos a la tabla
    for (Empleado empleado : empleados) {
        // Crear un arreglo con los datos del empleado
        Object[] fila = new Object[] {
            empleado.getId(),
            empleado.getNombre(),
            empleado.getCorreo(),
            empleado.getTelefono(),
            empleado.getDireccion(),
            empleado.getFechaIngreso(), // Este método ya devuelve un String
            empleado.getSalarioHora(),
            empleado.getPuesto().getNombre() // Obtener el nombre del puesto
        };

        // Agregar la fila al modelo de la tabla
        modelo.addRow(fila);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonModificarEmpleado = new javax.swing.JButton();
        ButtonEliminarEmpleado = new javax.swing.JButton();
        ButtonCrearEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Editor de Planilla de Empleados");

        ButtonModificarEmpleado.setBackground(new java.awt.Color(204, 102, 255));
        ButtonModificarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonModificarEmpleado.setText("Modificar Empleado");
        ButtonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarEmpleadoActionPerformed(evt);
            }
        });

        ButtonEliminarEmpleado.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEliminarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEliminarEmpleado.setText("Eliminar Empleado");
        ButtonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarEmpleadoActionPerformed(evt);
            }
        });

        ButtonCrearEmpleado.setBackground(new java.awt.Color(153, 255, 153));
        ButtonCrearEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCrearEmpleado.setText("Crear Empleado");
        ButtonCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearEmpleadoActionPerformed(evt);
            }
        });

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Nombre", "Correo", "Teléfono", "Dirección", "Fecha Ingreso", "Salario Hora", "Puesto"
            }
        ));
        jScrollPane1.setViewportView(TablaEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarEmpleadoActionPerformed
        // TODO add your handling code here:
        // Verificar que se haya seleccionado una fila de la tabla
        int filaSeleccionada = TablaEmpleados.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado para modificar.");
        } else {
            // Obtener los datos del empleado seleccionado en la fila
            String identificacion = TablaEmpleados.getValueAt(filaSeleccionada, 0).toString();
            
            // Crear una instancia de la ventana de modificación y pasarle el empleado
            ADMINModificarEmpleado ventanaModificarEmpleado = new ADMINModificarEmpleado(obra, identificacion);
            ventanaModificarEmpleado.setVisible(true);
        }
    }//GEN-LAST:event_ButtonModificarEmpleadoActionPerformed

    private void ButtonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
         // Verificar que se haya seleccionado una fila de la tabla
        int filaSeleccionada = TablaEmpleados.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado para eliminar.");
        } else {
            // Obtener los datos del empleado seleccionado en la fila
            String identificacion = TablaEmpleados.getValueAt(filaSeleccionada, 0).toString();
            
            obra.eliminarEmpleado(identificacion);
            javax.swing.JOptionPane.showMessageDialog(null, "Empleado eliminado exitosamente");
        }
    }//GEN-LAST:event_ButtonEliminarEmpleadoActionPerformed

    private void ButtonCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearEmpleadoActionPerformed
        // TODO add your handling code here:
        ADMINCrearEmpleado verCrearEmpleado = new ADMINCrearEmpleado(obra);    
        verCrearEmpleado.setVisible(true);
    }//GEN-LAST:event_ButtonCrearEmpleadoActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCrearEmpleado;
    private javax.swing.JButton ButtonEliminarEmpleado;
    private javax.swing.JButton ButtonModificarEmpleado;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
