/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*

NOTA IMPORTANTE:

Aqui hay que hacer código adicional tanto para cambiar la etiqueta como para
centrarla en cada caso


*/

package Vista;

import Modelo.Empleado;
import Negocio.Obra;
import Modelo.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amari
 */
public class ADMINEditorAdminsInspectores extends javax.swing.JFrame {

    /**
     * Creates new form PlanillaEmpleados
     */
    private Obra obra;
    
    public ADMINEditorAdminsInspectores(Obra obra) {
        this.obra = obra;
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Nombre");
        model.addColumn("Rol");

        TablaUsuarios.setModel(model);
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cargarUsuariosEnTabla();
        
    }

    // Método para rellenar la tabla con los datos del ArrayList<Empleado>
private void cargarUsuariosEnTabla() {
    // Obtener el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) TablaUsuarios.getModel();

    // Limpiar cualquier dato previo en la tabla
    modelo.setRowCount(0);

    // Obtener la lista de empleados
    ArrayList<Usuario> usuarios = obra.getListaUsuarios();

    // Recorrer el ArrayList y agregar los datos a la tabla
    for (Usuario usuario : usuarios) {
        // Crear un arreglo con los datos del empleado
        Object[] fila = new Object[] {
            usuario.getUsername(),
            usuario.getPassword(),
            usuario.getNombre(),
            usuario.getRol(),
        };

        // Agregar la fila al modelo de la tabla
        modelo.addRow(fila);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonModificarFuncionario = new javax.swing.JButton();
        ButtonEliminarFuncionario = new javax.swing.JButton();
        ButtonAgregarFuncionario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Editor de Usuarios");

        ButtonModificarFuncionario.setBackground(new java.awt.Color(204, 153, 255));
        ButtonModificarFuncionario.setText("Modificar funcionario");
        ButtonModificarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarFuncionarioActionPerformed(evt);
            }
        });

        ButtonEliminarFuncionario.setBackground(new java.awt.Color(255, 102, 102));
        ButtonEliminarFuncionario.setText("Eliminar funcionario");
        ButtonEliminarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarFuncionarioActionPerformed(evt);
            }
        });

        ButtonAgregarFuncionario.setBackground(new java.awt.Color(102, 255, 102));
        ButtonAgregarFuncionario.setText("Crear funcionario");
        ButtonAgregarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarFuncionarioActionPerformed(evt);
            }
        });

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Nombre", "Rol"
            }
        ));
        jScrollPane2.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(ButtonAgregarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonModificarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEliminarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonModificarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEliminarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAgregarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonModificarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarFuncionarioActionPerformed
        // TODO add your handling code here:
        // Verificar que se haya seleccionado una fila de la tabla
        int filaSeleccionada = TablaUsuarios.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para modificar.");
        } else {
            // Obtener los datos del empleado seleccionado en la fila
            String username = TablaUsuarios.getValueAt(filaSeleccionada, 0).toString();
            
            // Crear una instancia de la ventana de modificación y pasarle el empleado
            ADMINModificarFuncionario verModificarUsuario = new ADMINModificarFuncionario(obra, username);
            verModificarUsuario.setVisible(true);
        }
    }//GEN-LAST:event_ButtonModificarFuncionarioActionPerformed

    private void ButtonEliminarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarFuncionarioActionPerformed
        // TODO add your handling code here:
        // Verificar que se haya seleccionado una fila de la tabla
        int filaSeleccionada = TablaUsuarios.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para eliminar.");
        } else {
            // Obtener los datos del empleado seleccionado en la fila
            String identificacion = TablaUsuarios.getValueAt(filaSeleccionada, 0).toString();
            
            obra.eliminarUsuario(identificacion);
            javax.swing.JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
        }
        
    }//GEN-LAST:event_ButtonEliminarFuncionarioActionPerformed

    private void ButtonAgregarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarFuncionarioActionPerformed
        // TODO add your handling code here:
        ADMINCrearFuncionario verCrearFuncionario = new ADMINCrearFuncionario(obra);    
        verCrearFuncionario.setVisible(true);
    }//GEN-LAST:event_ButtonAgregarFuncionarioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregarFuncionario;
    private javax.swing.JButton ButtonEliminarFuncionario;
    private javax.swing.JButton ButtonModificarFuncionario;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
