/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Medida;
import Negocio.Obra;
import Modelo.Puesto;
import Modelo.Riesgo;
import java.awt.Image;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Ventana para consultar el puesto por el inspector
 */
public class INSPECTORConsultarPuesto extends javax.swing.JFrame {

    /**
     * Creates new form INSPECTORConsultarPuesto
     */
    private Obra obra;
    private String identificacion;
    private Puesto puestoModificando;
    
    public INSPECTORConsultarPuesto(Obra obra, String identificacion) {
        this.obra = obra;
        this.identificacion = identificacion;
        puestoModificando = obra.buscarPuesto(identificacion);       
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelPuesto.setText(puestoModificando.getNombre());
        
        String rutaImagen = puestoModificando.getRutaImagen();
        URL recurso = getClass().getResource(rutaImagen);
        
      if (recurso != null) {
            ImageIcon iconoImagen = new ImageIcon(recurso);
            Icon mIcono = new ImageIcon(iconoImagen.getImage()
                    .getScaledInstance(LabelFoto.getWidth(), LabelFoto.getHeight(), Image.SCALE_SMOOTH));
            LabelFoto.setIcon(mIcono);
        } else {
            LabelFoto.setText("Sin imagen");
            LabelFoto.setHorizontalAlignment(SwingConstants.CENTER);
        }
        
       
        cargarRiesgosEnTabla();
        cargarMedidasEnTabla();
    }
    
    // Método para cargar los riesgos en la tabla
    private void cargarRiesgosEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaRiesgos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Riesgo riesgo : puestoModificando.getRiesgos()) {
            modelo.addRow(new Object[]{riesgo.getNombre()});
        }
    }

    // Método para cargar las medidas en la tabla
    private void cargarMedidasEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMedidas.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Medida medida : puestoModificando.getMedidas()) {
            modelo.addRow(new Object[]{medida.getNombre()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelFoto = new javax.swing.JLabel();
        LabelPuesto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRiesgos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Puesto:");

        LabelPuesto.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        LabelPuesto.setText("_");

        tablaMedidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Medidas"
            }
        ));
        jScrollPane1.setViewportView(tablaMedidas);

        tablaRiesgos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Riesgos"
            }
        ));
        jScrollPane2.setViewportView(tablaRiesgos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LabelPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPuesto)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel LabelPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaMedidas;
    private javax.swing.JTable tablaRiesgos;
    // End of variables declaration//GEN-END:variables
}
