/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Empleado;
import Negocio.Obra;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amari
 */
public class INSPECTORVerEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form INSPECTORVerEmpleados
     */
    private Obra obra;
    
    public INSPECTORVerEmpleados(Obra obra) {
        this.obra = obra;
        
        System.out.println("\nNombre obra desde Planilla Empleados: " + obra.getNombre());
        
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Identificación");
        model.addColumn("Nombre");
        model.addColumn("Correo");
        model.addColumn("Teléfono");
        model.addColumn("Dirección");
        model.addColumn("Fecha Ingreso");
        model.addColumn("Salario Hora");
        model.addColumn("Puesto");

        TablaEmpleados.setModel(model);
        TablaEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cargarEmpleadosEnTabla();
   
        
    }

    // Método para rellenar la tabla con los datos del ArrayList<Empleado>
private void cargarEmpleadosEnTabla() {
    // Obtener el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) TablaEmpleados.getModel();

    // Limpiar cualquier dato previo en la tabla
    modelo.setRowCount(0);

    // Obtener la lista de empleados
    ArrayList<Empleado> empleados = obra.getPlanillaEmpleados();

    // Recorrer el ArrayList y agregar los datos a la tabla
    for (Empleado empleado : empleados) {
        // Crear un arreglo con los datos del empleado
        Object[] fila = new Object[] {
            empleado.getId(),
            empleado.getNombre(),
            empleado.getCorreo(),
            empleado.getTelefono(),
            empleado.getDireccion(),
            empleado.getFechaIngreso(), // Este método ya devuelve un String
            empleado.getSalarioHora(),
            empleado.getPuesto().getNombre() // Obtener el nombre del puesto
        };

        // Agregar la fila al modelo de la tabla
        modelo.addRow(fila);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonRealizarInspeccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Consultar Planilla de Empleados");

        ButtonRealizarInspeccion.setText("Realizar Inspección");
        ButtonRealizarInspeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRealizarInspeccionActionPerformed(evt);
            }
        });

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Nombre", "Correo", "Teléfono", "Dirección", "Fecha Ingreso", "Salario Hora", "Puesto"
            }
        ));
        jScrollPane2.setViewportView(TablaEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonRealizarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(ButtonRealizarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRealizarInspeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRealizarInspeccionActionPerformed
        // TODO add your handling code here:
         // Verificar que se haya seleccionado una fila de la tabla
        int filaSeleccionada = TablaEmpleados.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado para hacerle la inspección.");
        } else {
            // Obtener los datos del empleado seleccionado en la fila
            String identificacion = TablaEmpleados.getValueAt(filaSeleccionada, 0).toString();
            
            // Crear una instancia de la ventana de modificación y pasarle el empleado
            INSPECTORHacerInspeccion verInspeccion = new INSPECTORHacerInspeccion(obra, identificacion);    
            verInspeccion.setVisible(true);
        }
        
        
    }//GEN-LAST:event_ButtonRealizarInspeccionActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRealizarInspeccion;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
