/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Empleado;
import Modelo.EntradaBitacora;
import Modelo.Medida;
import Negocio.Obra;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Ventana para hacer la inspección
 */
public class INSPECTORHacerInspeccion extends javax.swing.JFrame {

    private Obra obra;
    private String identificacion;
    private Empleado empleadoModificando;
    
    public INSPECTORHacerInspeccion(Obra obra, String identificacion) {
        this.obra = obra;       
        this.identificacion = identificacion;
        
        empleadoModificando = obra.buscarEmpleado(identificacion);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        
        LabelEmpleado.setText(empleadoModificando.getNombre());
        LabelPuesto.setText(empleadoModificando.getPuesto().getNombre());
        
        Calendar fechaActual = Calendar.getInstance();
        //entradaBitacora.setFechaInspeccion(fechaActual);

        // Formatear la fecha
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaFormateada = formatoFecha.format(fechaActual.getTime());

        // Mostrar en el label
        LabelFecha.setText(fechaFormateada);
        cargarMedidasEnTabla();

    }
    
    // Método para cargar las medidas en la tabla
    private void cargarMedidasEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaMedidas.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Medida medida : empleadoModificando.getPuesto().getMedidas()) {
            modelo.addRow(new Object[]{medida.getNombre()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextInspector = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedidas = new javax.swing.JTable();
        ButtonGuardarInspeccion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextObservaciones = new javax.swing.JTextArea();
        LabelFecha = new javax.swing.JLabel();
        LabelEmpleado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelPuesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Inspección");

        jLabel2.setText("Inspección realizada por:");

        jLabel3.setText("Fecha de inspección:");

        jLabel4.setText("Empleado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Resultados:");

        tablaMedidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Medidas cumplidas"
            }
        ));
        jScrollPane1.setViewportView(tablaMedidas);

        ButtonGuardarInspeccion.setBackground(new java.awt.Color(255, 102, 204));
        ButtonGuardarInspeccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonGuardarInspeccion.setText("Guardar Inspección");
        ButtonGuardarInspeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarInspeccionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Observaciones:");

        TextObservaciones.setColumns(20);
        TextObservaciones.setRows(5);
        jScrollPane2.setViewportView(TextObservaciones);

        LabelFecha.setText("_");

        LabelEmpleado.setText("_");

        jLabel7.setText("Puesto:");

        LabelPuesto.setText("_");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonGuardarInspeccion)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextInspector, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LabelEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(LabelFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LabelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextInspector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabelPuesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ButtonGuardarInspeccion))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGuardarInspeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarInspeccionActionPerformed
        // TODO add your handling code here:
        // Recuperar los datos ingresados en los campos de texto y el combo box
    String nombreInspector = TextInspector.getText();
    String observacion = TextObservaciones.getText();
   
    // Validar si todos los campos están completos y los datos son correctos (ejemplo: validación del formato de fecha)
    if (nombreInspector.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escriba el nombre del inspector");
        return;
    }
    
    if (!obra.buscarInspector(nombreInspector)){
        javax.swing.JOptionPane.showMessageDialog(this, "Usuario ingresado no puede realizar una inspección");
        return;
    }
    
    // Validar si todos los campos están completos y los datos son correctos (ejemplo: validación del formato de fecha)
    if (observacion.isEmpty()) {
        observacion = "---";
    }
    Calendar fechaActual = Calendar.getInstance();
    
    // Crear los ArrayList para medidas cumplidas y faltas
    ArrayList<Medida> cumplidas = new ArrayList<>();
    ArrayList<Medida> faltas = new ArrayList<>();

    // Obtener el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) tablaMedidas.getModel();

    // Iterar por las filas de la tabla
    for (int i = 0; i < modelo.getRowCount(); i++) {
        String medidaNombre = modelo.getValueAt(i, 0).toString().trim(); // Asumiendo que el nombre está en la primera columna

        // Recuperar la instancia de Medida usando el nombre
        Medida medida = empleadoModificando.getPuesto().getMedida(medidaNombre);

        if (tablaMedidas.isRowSelected(i)) {
            // Si la fila está seleccionada, agregar a cumplidas
            cumplidas.add(medida);
        } else {
            // Si no está seleccionada, agregar a faltas
            faltas.add(medida);
        }
    }

    // Crear una nueva instancia de EntradaBitacora
    EntradaBitacora entrada = new EntradaBitacora(nombreInspector, fechaActual, 
            empleadoModificando, cumplidas, faltas, observacion);

    // Agregar la entrada a la bitácora de la obra
    obra.getBitacora().add(entrada);

    System.out.println(obra.getBitacora().toString());
    
    // Confirmar al usuario
    JOptionPane.showMessageDialog(null, "Inspección guardada correctamente.");
    
        
    
    
    
    }//GEN-LAST:event_ButtonGuardarInspeccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGuardarInspeccion;
    private javax.swing.JLabel LabelEmpleado;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelPuesto;
    private javax.swing.JTextField TextInspector;
    private javax.swing.JTextArea TextObservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaMedidas;
    // End of variables declaration//GEN-END:variables
}
