/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.Obra;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * Ventana principal para los Inspectores
 */
public class PrincipalInspectores extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalInspectores
     */
    private Obra obra;
    public PrincipalInspectores(Obra obra) {
        this.obra = obra;
        
        
        
        System.out.println("Desde la ventana Principal ADMINS:" +  obra.getCodigo()+  obra.getNombre());
       
        
        initComponents();      
        
         addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
             onExit();
           }
          });
        
     //   setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
     

    }


    public void onExit() {
        
        try {
            obra.guardarPlanillas();
            System.out.println("Cambios guardados correctamente.");
        } catch (Exception e) {
            System.err.println("Error al guardar las planillas: " + e.getMessage());
        }

        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelFoto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuConsultarEmpleados = new javax.swing.JMenuItem();
        MenuConsultarPuestos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuConsultarBitacora = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuEnviarBitacora = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 30));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inspector");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        LabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Inspector.png"))); // NOI18N
        jPanel1.add(LabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 710, 400));

        jMenu1.setText("Consultar");

        MenuConsultarEmpleados.setText("Empleados");
        MenuConsultarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuConsultarEmpleados);

        MenuConsultarPuestos.setText("Puestos");
        MenuConsultarPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarPuestosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuConsultarPuestos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bitácora");

        MenuConsultarBitacora.setText("Consultar bitácora");
        MenuConsultarBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarBitacoraActionPerformed(evt);
            }
        });
        jMenu2.add(MenuConsultarBitacora);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Correo");

        MenuEnviarBitacora.setText("Enviar bitácora");
        MenuEnviarBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEnviarBitacoraActionPerformed(evt);
            }
        });
        jMenu3.add(MenuEnviarBitacora);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuConsultarPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarPuestosActionPerformed
        // TODO add your handling code here:
        INSPECTORVerPuestos verPuestos = new INSPECTORVerPuestos(obra);    
        verPuestos.setVisible(true);
        
    }//GEN-LAST:event_MenuConsultarPuestosActionPerformed

    private void MenuConsultarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarEmpleadosActionPerformed
        // TODO add your handling code here:
        INSPECTORVerEmpleados verPlanillaEmpleados = new INSPECTORVerEmpleados(obra);    
        verPlanillaEmpleados.setVisible(true);  
    }//GEN-LAST:event_MenuConsultarEmpleadosActionPerformed

    private void MenuConsultarBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarBitacoraActionPerformed
        // TODO add your handling code here:
        AMBOSConsultarBitacora verBitacora = new AMBOSConsultarBitacora(obra);    
        verBitacora.setVisible(true);  
    }//GEN-LAST:event_MenuConsultarBitacoraActionPerformed

    private void MenuEnviarBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEnviarBitacoraActionPerformed
        // TODO add your handling code here:
        INSPECTOREnviarBitacoraCorreo verEnviarBitacora = new INSPECTOREnviarBitacoraCorreo(obra);    
        verEnviarBitacora.setVisible(true);
    }//GEN-LAST:event_MenuEnviarBitacoraActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        try {
            obra.guardarPlanillas();
            System.out.println("Cambios guardados correctamente.");
        } catch (Exception e) {
            System.err.println("Error al guardar las planillas: " + e.getMessage());
        }

        // Salir del sistema
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JMenuItem MenuConsultarBitacora;
    private javax.swing.JMenuItem MenuConsultarEmpleados;
    private javax.swing.JMenuItem MenuConsultarPuestos;
    private javax.swing.JMenuItem MenuEnviarBitacora;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
