/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.Obra;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * Ventana principal para administradores 
 */
public class PrincipalAdmins extends javax.swing.JFrame {

    /**
     * Ventana Principal para los Admins
     */
    private Obra obra;
    
    public PrincipalAdmins(Obra obra) {
        this.obra = obra;
        System.out.println("Desde la ventana Principal ADMINS:" +  obra.getCodigo()+  obra.getNombre());
       
        
        
        
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
             onExit();
           }
          });
        
      //  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    public void onExit() {
        
        try {
            obra.guardarPlanillas();
            System.out.println("Cambios guardados correctamente.");
        } catch (Exception e) {
            System.err.println("Error al guardar las planillas: " + e.getMessage());
        }

        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelFoto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuVerEmpleados = new javax.swing.JMenuItem();
        MenuVerInspectores = new javax.swing.JMenuItem();
        MenuVerPuestos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuConsultarBitácora = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        LabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Administr.png"))); // NOI18N
        jPanel1.add(LabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        jMenu1.setText("Ver planilla");

        MenuVerEmpleados.setText("Empleados");
        MenuVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuVerEmpleados);

        MenuVerInspectores.setText("Usuarios");
        MenuVerInspectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerInspectoresActionPerformed(evt);
            }
        });
        jMenu1.add(MenuVerInspectores);

        MenuVerPuestos.setText("Puestos");
        MenuVerPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerPuestosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuVerPuestos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        MenuConsultarBitácora.setText("Consultar bitácora");
        MenuConsultarBitácora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarBitácoraActionPerformed(evt);
            }
        });
        jMenu2.add(MenuConsultarBitácora);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuConsultarBitácoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarBitácoraActionPerformed
        // TODO add your handling code here:
        AMBOSConsultarBitacora verBitacora = new AMBOSConsultarBitacora(obra);    
        verBitacora.setVisible(true);          
    }//GEN-LAST:event_MenuConsultarBitácoraActionPerformed

    private void MenuVerInspectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerInspectoresActionPerformed
        // TODO add your handling code here:
        ADMINEditorAdminsInspectores verEditorAdminInspectores = new ADMINEditorAdminsInspectores(obra);    
        verEditorAdminInspectores.setVisible(true);        
    }//GEN-LAST:event_MenuVerInspectoresActionPerformed

    private void MenuVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerEmpleadosActionPerformed
        // TODO add your handling code here:
        ADMINEditorEmpleados verPlanillaEmpleados = new ADMINEditorEmpleados(obra);    
        verPlanillaEmpleados.setVisible(true);  
        
    }//GEN-LAST:event_MenuVerEmpleadosActionPerformed

    private void MenuVerPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerPuestosActionPerformed
        // TODO add your handling code here:
        ADMINEditorPuestos verEditorPuestos = new ADMINEditorPuestos(obra);
        verEditorPuestos.setVisible(true);
    }//GEN-LAST:event_MenuVerPuestosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        try {
            obra.guardarPlanillas();
            System.out.println("Cambios guardados correctamente.");
        } catch (Exception e) {
            System.err.println("Error al guardar las planillas: " + e.getMessage());
        }

        // Salir del sistema
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JMenuItem MenuConsultarBitácora;
    private javax.swing.JMenuItem MenuVerEmpleados;
    private javax.swing.JMenuItem MenuVerInspectores;
    private javax.swing.JMenuItem MenuVerPuestos;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
